name: Setup Node LTS
description: Setup Node.js
runs:
  using: composite

  steps:
    - name: Enable Corepack
      run: corepack enable && corepack install
      shell: bash

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: yarn
        node-version: lts/*

    - name: Install dependencies
      run: yarn
      shell: bash
