name: ci

on: push

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Checkout
        uses: actions/checkout@master

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --immutable

  suite:
    needs: prepare
    name: Suite
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Checkout
        uses: actions/checkout@master

      - name: Retrieve node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format:check

      - name: Typecheck
        run: yarn typecheck

      - name: Build
        run: yarn build
