// Code generated by Slice Machine. DO NOT EDIT.
import type * as prismic from "@prismicio/client"

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		| prismic.AnyRegularField
		| prismic.GroupField
		| prismic.NestedGroupField
		| prismic.SliceZone
	>,
	TLang extends string,
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
			TSubRelationship["customtypes"],
			TLang
		>
	} & { // Group
		[TGroup in Extract<
			TRelationship["fields"][number],
			| prismic.CustomTypeModelFetchGroupLevel1
			| prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
			infer TGroupData
		>
			? prismic.GroupField<
					PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
				>
			: never
	} & { // Other fields
		[TFieldKey in Extract<
			TRelationship["fields"][number],
			string
		>]: TFieldKey extends keyof TData ? TData[TFieldKey] : never
	}

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string,
> = {
	[ID in Exclude<
		TCustomType[number],
		string
	>["id"]]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
			TLang
		>
	>
}[Exclude<TCustomType[number], string>["id"]]

/**
 * Item in _Navigation → Links_
 */
export interface NavigationDocumentDataLinksItem {
	/**
	 * Label field in _Navigation → Links_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Optional - Label for the link
	 * - **API ID Path**: navigation.links[].label
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	label: prismic.RichTextField

	/**
	 * Link field in _Navigation → Links_
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Link for navigation item
	 * - **API ID Path**: navigation.links[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
	/**
	 * Links field in _Navigation_
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: _None_
	 * - **API ID Path**: navigation.links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<NavigationDocumentData>,
		"navigation",
		Lang
	>

type PageDocumentDataSlicesSlice =
	| HeroSlice
	| QuoteSlice
	| TextSlice
	| ImageSlice
	| ImageCardsSlice
	| TextWithImageSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in _Page_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField

	/**
	 * Parent field in _Page_
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: _None_
	 * - **API ID Path**: page.parent
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	parent: prismic.ContentRelationshipField<"page">

	/**
	 * Slice Zone field in _Page_
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: _None_
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in _Page_
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search
	 *   engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in _Page_
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in _Page_
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: _None_
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * Site Title field in _Settings_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Title of the site
	 * - **API ID Path**: settings.siteTitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	siteTitle: prismic.RichTextField
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<SettingsDocumentData>,
		"settings",
		Lang
	>

export type AllDocumentTypes =
	| NavigationDocument
	| PageDocument
	| SettingsDocument

/**
 * Primary content in _Hero → Default → Primary_
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Title field in _Hero → Default → Primary_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField

	/**
	 * Description field in _Hero → Default → Primary_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: hero.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField

	/**
	 * Cta Link field in _Hero → Default → Primary_
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: _None_
	 * - **API ID Path**: hero.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.Repeatable<
		prismic.LinkField<
			string,
			string,
			unknown,
			prismic.FieldState,
			"Primary" | "Secondary" | "Text"
		>
	>

	/**
	 * anchor field in _Hero → Default → Primary_
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: optional
	 * - **API ID Path**: hero.default.primary.anchor
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	anchor: prismic.KeyTextField
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<HeroSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for _Hero_
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>

/**
 * Primary content in _Quote → Default → Primary_
 */
export interface QuoteSliceDefaultPrimary {
	/**
	 * Quote field in _Quote → Default → Primary_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: quote.default.primary.quote
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	quote: prismic.RichTextField

	/**
	 * Source field in _Quote → Default → Primary_
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: quote.default.primary.source
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	source: prismic.KeyTextField
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<QuoteSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for _Quote_
 */
type QuoteSliceVariation = QuoteSliceDefault

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>

/**
 * Primary content in _Image → Default → Primary_
 */
export interface ImageSliceDefaultPrimary {
	/**
	 * Image field in _Image → Default → Primary_
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<ImageSliceDefaultPrimary>,
	never
>

/**
 * Primary content in _Image → Banner → Primary_
 */
export interface ImageSliceBannerPrimary {
	/**
	 * Image field in _Image → Banner → Primary_
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image.banner.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>
}

/**
 * Banner variation for Image Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceBanner = prismic.SharedSliceVariation<
	"banner",
	Simplify<ImageSliceBannerPrimary>,
	never
>

/**
 * Slice variation for _Image_
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceBanner

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>

/**
 * Primary content in _TextWithImage → Default → Primary_
 */
export interface TextWithImageSliceDefaultPrimary {
	/**
	 * Text field in _TextWithImage → Default → Primary_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: text_with_image.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField

	/**
	 * Image field in _TextWithImage → Default → Primary_
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: _None_
	 * - **API ID Path**: text_with_image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>
}

/**
 * Default variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<TextWithImageSliceDefaultPrimary>,
	never
>

/**
 * Primary content in _TextWithImage → With Button → Primary_
 */
export interface TextWithImageSliceWithButtonPrimary {
	/**
	 * Text field in _TextWithImage → With Button → Primary_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: text_with_image.withButton.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField

	/**
	 * Button Link field in _TextWithImage → With Button → Primary_
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: _None_
	 * - **API ID Path**: text_with_image.withButton.primary.buttonLink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	buttonLink: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>

	/**
	 * Button Text field in _TextWithImage → With Button → Primary_
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: text_with_image.withButton.primary.buttonText
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	buttonText: prismic.KeyTextField

	/**
	 * Image field in _TextWithImage → With Button → Primary_
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: _None_
	 * - **API ID Path**: text_with_image.withButton.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>
}

/**
 * With Button variation for TextWithImage Slice
 *
 * - **API ID**: `withButton`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextWithImageSliceWithButton = prismic.SharedSliceVariation<
	"withButton",
	Simplify<TextWithImageSliceWithButtonPrimary>,
	never
>

/**
 * Slice variation for _TextWithImage_
 */
type TextWithImageSliceVariation =
	| TextWithImageSliceDefault
	| TextWithImageSliceWithButton

/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextWithImageSlice = prismic.SharedSlice<
	"text_with_image",
	TextWithImageSliceVariation
>

/**
 * Primary content in _Text → Default → Primary_
 */
export interface TextSliceDefaultPrimary {
	/**
	 * Text field in _Text → Default → Primary_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: text.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<TextSliceDefaultPrimary>,
	never
>

/**
 * Primary content in _Text → Two Columns → Primary_
 */
export interface TextSliceTwoColumnsPrimary {
	/**
	 * Text field in _Text → Two Columns → Primary_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: text.twoColumns.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField
}

/**
 * Two Columns variation for Text Slice
 *
 * - **API ID**: `twoColumns`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceTwoColumns = prismic.SharedSliceVariation<
	"twoColumns",
	Simplify<TextSliceTwoColumnsPrimary>,
	never
>

/**
 * Slice variation for _Text_
 */
type TextSliceVariation = TextSliceDefault | TextSliceTwoColumns

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>

/**
 * Item in _ImageCards → Default → Primary → Cards_
 */
export interface ImageCardsSliceDefaultPrimaryCardsItem {
	/**
	 * Image field in _ImageCards → Default → Primary → Cards_
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image_cards.default.primary.cards[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>

	/**
	 * Text field in _ImageCards → Default → Primary → Cards_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image_cards.default.primary.cards[].text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField

	/**
	 * Button Link field in _ImageCards → Default → Primary → Cards_
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image_cards.default.primary.cards[].buttonLink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	buttonLink: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>

	/**
	 * Button Text field in _ImageCards → Default → Primary → Cards_
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image_cards.default.primary.cards[].buttonText
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	buttonText: prismic.KeyTextField
}

/**
 * Primary content in _ImageCards → Default → Primary_
 */
export interface ImageCardsSliceDefaultPrimary {
	/**
	 * Heading field in _ImageCards → Default → Primary_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image_cards.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField

	/**
	 * Cards field in _ImageCards → Default → Primary_
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: _None_
	 * - **API ID Path**: image_cards.default.primary.cards[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	cards: prismic.GroupField<Simplify<ImageCardsSliceDefaultPrimaryCardsItem>>
}

/**
 * Default variation for ImageCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCardsSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<ImageCardsSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for _ImageCards_
 */
type ImageCardsSliceVariation = ImageCardsSliceDefault

/**
 * ImageCards Shared Slice
 *
 * - **API ID**: `image_cards`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCardsSlice = prismic.SharedSlice<
	"image_cards",
	ImageCardsSliceVariation
>

declare module "@prismicio/client" {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig,
		): prismic.WriteClient<AllDocumentTypes>
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>
	}

	namespace Content {
		export type {
			NavigationDocument,
			NavigationDocumentData,
			NavigationDocumentDataLinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			AllDocumentTypes,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			QuoteSlice,
			QuoteSliceDefaultPrimary,
			QuoteSliceVariation,
			QuoteSliceDefault,
			ImageSlice,
			ImageSliceDefaultPrimary,
			ImageSliceBannerPrimary,
			ImageSliceVariation,
			ImageSliceDefault,
			ImageSliceBanner,
			TextWithImageSlice,
			TextWithImageSliceDefaultPrimary,
			TextWithImageSliceWithButtonPrimary,
			TextWithImageSliceVariation,
			TextWithImageSliceDefault,
			TextWithImageSliceWithButton,
			TextSlice,
			TextSliceDefaultPrimary,
			TextSliceTwoColumnsPrimary,
			TextSliceVariation,
			TextSliceDefault,
			TextSliceTwoColumns,
			ImageCardsSlice,
			ImageCardsSliceDefaultPrimaryCardsItem,
			ImageCardsSliceDefaultPrimary,
			ImageCardsSliceVariation,
			ImageCardsSliceDefault,
		}
	}
}
