name: ci

on:
  push:
  workflow_call:

jobs:
  suite:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format:check

      - name: Typecheck
        run: yarn typecheck

      - name: Build
        run: yarn build
